openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a REST API for managing user contacts. Supports authentication via JWT.
tags:
  - name: contacts
    description: Contact operations
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-v182.onrender.com
paths:
  /auth/login:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/register:
      $ref: ../swagger/paths/auth/register.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/delete.yaml
components:
  schemas:
    userRequest:
      $ref: ../swagger/components/schemas/userRequest.yaml
    contact:
      $ref: ../swagger/components/schemas/contact.yaml
  responses:
    200:
      $ref: ../swagger/components/responses/200.yaml
    201:
      $ref: ../swagger/components/responses/201.yaml
    401:
      $ref: ../swagger/components/responses/401.yaml
    404:
      $ref: ../swagger/components/responses/404.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
